Hack Ebola
==================
<!--
    ```
-->
```{r, message = FALSE, tidy = FALSE, echo = F}
## knitr configuration: http://yihui.name/knitr/options#chunk_options
showMessage <- FALSE
showWarning <- TRUE
set_alias(w = "fig.width", h = "fig.height", res = "results")
opts_chunk$set(comment = "##", error= TRUE, warning = showWarning, message = showMessage,
               tidy = FALSE, cache = F, echo = T,
               fig.width = 7, fig.height = 7, dev.args = list(family = "sans"))
## for rgl
knit_hooks$set(rgl = hook_rgl, webgl = hook_webgl)
## for animation
opts_knit$set(animation.fun = hook_ffmpeg_html)

## R configuration
options(width = 116, scipen = 5)
```
<!--
    ``` ```
-->

References
--------------------

Load packages
--------------------
```{r}
library(magrittr)
library(gpairs)
library(ggplot2)
library(ggmap)
library(directlabels)

```

Load data
--------------------
```{r}
load(file = "dataList.RData")

```

Summary of the main dataset (2.csv)
--------------------
```{r}
## Extract main dataset
maindat <- dataList[[2]]
## Fix date
maindat$date <- maindat$date + as.Date("1899-12-31")
##
summary(maindat)
##
head(maindat)
## Number of records by Countries
maindat %>% extract("country") %>% table
## Number of records by Regions and Countries
xtabs( ~ sdr_name + country, maindat)
## 
cat("### Types of cases by regions\n")
xtabs( ~ sdr_name + category, data = subset(maindat, sdr_level == "ADM2"))

```

Plot
--------------------
```{r, w = 15, h = 15}
plot1 <- ggplot(data = subset(maindat, sdr_level == "ADM2"),
       mapping = aes(x = date, y = value, group = sdr_name, color = sdr_name)) +
           layer(geom = "line") +
           guides(color = guide_legend(ncol = 2)) +
           facet_wrap( ~ category, ncol = 2) + 
           theme_bw() + theme(legend.key = element_blank())
plot1

```

Geocodes
--------------------
```{r}
geodat <- dataList[[1]]

ggplot(data = geodat, mapping = aes(x = gn_longitude, y = gn_latitude, label = name)) +
    layer(geom = "point") + 
    ## layer(geom = "text", size = 3) +
    theme_bw() + theme(legend.key = element_blank())

```

Plot areas where cases are reported
--------------------
```{r}
## Extract geocode data for sdr_name existing in maindat
geodatInclded <- geodat[geodat$name %in% maindat$sdr_name, ]

## ggmap
qmplot(x = gn_longitude, y = gn_latitude, data = geodatInclded, source = "google")

```


Liberia
--------------------
```{r}
## Extract Liberia administrative level 2 data
geodatLiberia <- subset(geodat, country_code == "LR" & level == "ADM1")

geodatLiberia$ebola <- geodatLiberia$name %in% maindat$sdr_name

qmplot(x = gn_longitude, y = gn_latitude, color = factor(ebola, levels = c(TRUE,FALSE)),
       data = geodatLiberia, source = "google")

## Distance matrix
matLatDist <- outer(X = geodatLiberia[,c("gn_latitude")],
                    Y = geodatLiberia[,c("gn_latitude")],
                    FUN = function(X,Y) {(X-Y)^2})
matLonDist <- outer(X = geodatLiberia[,c("gn_longitude")],
                    Y = geodatLiberia[,c("gn_longitude")],
                    FUN = function(X,Y) {(X-Y)^2})
matSqDist <- matLatDist + matLonDist %>% sqrt

## Sort each row
matSqDistSort <- apply(matSqDist, MARGIN = 1, FUN = sort) %>% t

```


--------------------
- Top Page: http://rpubs.com/kaz_yos/
- Table of Contents: http://rpubs.com/kaz_yos/toc
- Table of Contents (Japanese): http://rpubs.com/kaz_yos/toc-j
- github: https://github.com/kaz-yos








